### ISSUE TITLE
data-ipa-cfg-mgr

### ISSUE THREAD

**Issue by qiangua2460** [DevelopedInside/android_device_nubia_msm8998-common#4]
vendor/qcom/opensource/data-ipa-cfg-mgr/ipanat/src/ipa_nat_drvi.c:2205:25: error: use of undeclared identifier 'IPAHAL_NAT_INVALID_PROTOCOL'
                                        PROTOCOL_FIELD) == IPAHAL_NAT_INVALID_PROTOCOL
                                                           ^
1 error generated.

**Comment by tronnayan** [comment]
How you solved this issue

**Comment by qiangua2460** [comment]
> 您如何解决此问题
IPAHAL_NAT_INVALID_PROTOCOL commits

**Comment by tronnayan** [comment]
Can you provide the link to that link please

**Comment by qiangua2460** [comment]
> 您能否提供指向该链接的链接
搜索撒!

**Comment by tronnayan** [comment]
I have searched alot sir , please help me find the commit

**Comment by qiangua2460** [comment]
> > 您能否提供指向该链接的链接
> > 搜索撒!
问题都是公开

**Comment by tronnayan** [comment]
Github Gerrit and Google all I searched

**Comment by tronnayan** [comment]
Sir kindly use English please Google is not able to translate it all , and I cannot understand

**Comment by qiangua2460** [comment]
> 我搜索了很多先生，请帮助我找到提交
某些编译大神编译的内核某项中少语句

**Comment by tronnayan** [comment]
How to fix please guide

**Comment by qiangua2460** [comment]
> 先生，请使用英语，请Google无法翻译全部内容，我听不懂

我也不会英语列

**Comment by tronnayan** [comment]
先生，请告诉我如何解决

**Comment by tronnayan** [comment]
请提供提交的链接

**Comment by qiangua2460** [comment]
> 请提供提交的链


> 请提供提交的链接

include/uapi/linux/msm_ipa.h
少这个语句/**
 * name for default value of invalid protocol of NAT
 */
#define IPAHAL_NAT_INVALID_PROTOCOL   0xFF

**Comment by qiangua2460** [comment]
> > 请提供提交的链
> 
> > 请提供提交的链接
> 
> include/uapi/linux/msm_ipa.h
> 少这个语句/**
> 
> * name for default value of invalid protocol of NAT
>   */
>   #define IPAHAL_NAT_INVALID_PROTOCOL   0xFF

我也是最近才搜索到解决方法

**Comment by qiangua2460** [comment]
> > > 请提供提交的链
> > 
> > 
> > > 请提供提交的链接
> > 
> > 
> > include/uapi/linux/msm_ipa.h
> > 少这个语句/**
> > 
> > * name for default value of invalid protocol of NAT
> >   */
> >   #define IPAHAL_NAT_INVALID_PROTOCOL   0xFF
> 
> 我也是最近才搜索到解决方法

为什么要用中文回复您，中文翻译成英语，翻译过来的语言，都是词不达意的，怕您造成误解😊
